# Generated by Django 4.0.5 on 2022-06-05 18:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_alter_post_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post',
            field=tinymce.models.HTMLField(default='Some String'),
        ),
    ]
